Repository PHPCSStandards/PHPCSExtra, pull requests merged in 2023-07, with the labels that each got.

#250 GH Actions: special case Dependabot PRs for Coveralls
  .github/workflows/test.yml
Labels: Type: chores/QA

#251 Universal/DuplicateArrayKey: minor efficiency tweak
  Universal/Sniffs/Arrays/DuplicateArrayKeySniff.php
Labels: Type: chores/QA, Feature: Universal

#252 Universal/ConstructorDestructorReturn: minor efficiency tweak
  Universal/Sniffs/CodeAnalysis/ConstructorDestructorReturnSniff.php
Labels: Type: chores/QA, Feature: Universal

#253 GH Actions: update for php-coveralls 2.6.0
  .github/workflows/test.yml
Labels: Type: chores/QA

#255 Minor docs tweaks
  Universal/Docs/CodeAnalysis/NoEchoSprintfStandard.xml
  Universal/Tests/FunctionDeclarations/NoLongClosuresUnitTest.php
  Universal/Tests/UseStatements/DisallowMixedGroupUseUnitTest.php
Labels: Type: documentation

#256 Changelog and readme updates for PHPCSExtra 1.1.0
  CHANGELOG.md
  README.md
Labels: Type: documentation, Type: meta

#258 Fix typos
  Modernize/ruleset.xml
  Universal/Docs/CodeAnalysis/StaticInFinalClassStandard.xml
  Universal/Tests/CodeAnalysis/StaticInFinalClassUnitTest.inc
  Universal/Tests/CodeAnalysis/StaticInFinalClassUnitTest.inc.fixed
Labels: Type: chores/QA

#259 README: fix order of the sniff list
  README.md
Labels: Type: documentation
