Repository PHPCSStandards/PHPCSExtra, pull requests merged in 2023-11, with the labels that each got.

#276 :sparkles: New `Universal.PHP.LowercasePHPTag` sniff
  Universal/Docs/PHP/LowercasePHPTagStandard.xml
  Universal/Sniffs/PHP/LowercasePHPTagSniff.php
  Universal/Tests/PHP/LowercasePHPTagUnitTest.inc
  Universal/Tests/PHP/LowercasePHPTagUnitTest.inc.fixed
  Universal/Tests/PHP/LowercasePHPTagUnitTest.php
Labels: Type: enhancement, Feature: Universal

#277 :sparkles: New `Universal.CodeAnalysis.NoDoubleNegative` sniff
  Universal/Docs/CodeAnalysis/NoDoubleNegativeStandard.xml
  Universal/Sniffs/CodeAnalysis/NoDoubleNegativeSniff.php
  Universal/Tests/CodeAnalysis/NoDoubleNegativeUnitTest.inc
  Universal/Tests/CodeAnalysis/NoDoubleNegativeUnitTest.inc.fixed
  Universal/Tests/CodeAnalysis/NoDoubleNegativeUnitTest.php
Labels: Type: enhancement, Feature: Universal

#287 GH Actions: various tweaks
  .github/workflows/basics.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .yamllint.yml
  phpstan.neon.dist
Labels: Type: chores/QA

#288 Defer to organisation security policy
  .github/SECURITY.md
Labels: Type: documentation, Type: chores/QA

#289 GH Actions: switch to Coveralls action runner to upload reports
  .github/workflows/test.yml
Labels: Type: chores/QA

#284 Split the errors, adding the *CloserSameLine ones
  NormalizedArrays/Sniffs/Arrays/CommaAfterLastSniff.php
  NormalizedArrays/Tests/Arrays/CommaAfterLastUnitTest.1.inc
  NormalizedArrays/Tests/Arrays/CommaAfterLastUnitTest.1.inc.fixed
  NormalizedArrays/Tests/Arrays/CommaAfterLastUnitTest.php
Labels: Type: enhancement, Status: awaiting feedback, Feature: NormalizedArrays

#290 GH Actions: automate some label management
  .github/workflows/label-remove-outdated.yml
Labels: Type: chores/QA

#291 Composer.json: add link to security policy
  composer.json
Labels: Type: documentation

#292 GH Actions: update for the release of PHP 8.3
  .github/workflows/test.yml
  README.md
Labels: Type: chores/QA

#293 Universal/NoUselessAliases: remove unused constant
  Universal/Sniffs/UseStatements/NoUselessAliasesSniff.php
Labels: Type: chores/QA, Feature: Universal
